version: 1.0.{build}

environment:
  MSBUILD_FLAGS: /v:m
  matrix:
  - job_name: vs_2015
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GEN_NAME: Visual Studio 14 2015 Win64
    CMAKE_ARCH_ARG: ""
  - job_name: vs_2017
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    CMAKE_GEN_NAME: Visual Studio 15 2017 Win64
    CMAKE_ARCH_ARG: ""
  - job_name: vs_2019
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    CMAKE_GEN_NAME: Visual Studio 16 2019
    CMAKE_ARCH_ARG: "-A x64"

install:
  - choco install make

build_script:
  - make generate_windows build_windows

test_script:
  - make test_windows
