jobs:
  - job: linux_gcc_5
    displayName: Linux - GCC 5
    pool:
      vmImage: ubuntu-22.04
    variables:
      compiler: gcc
      version: 5
    steps:
      - bash: make generate_linux build_linux
        displayName: Build
      - bash: make test_linux
        displayName: Test
  - job: linux_gcc_9
    displayName: Linux - GCC 9
    pool:
      vmImage: ubuntu-22.04
    variables:
      compiler: gcc
      version: 9
    steps:
      - bash: make generate_linux build_linux
        displayName: Build
      - bash: make test_linux
        displayName: Test
  - job: linux_clang_37
    displayName: Linux - Clang 3.7
    pool:
      vmImage: ubuntu-22.04
    variables:
      compiler: clang
      version: 3.7
    steps:
      - bash: make generate_linux build_linux
        displayName: Build
      - bash: make test_linux
        displayName: Test
  - job: linux_clang_9
    displayName: Linux - Clang 9
    pool:
      vmImage: ubuntu-22.04
    variables:
      compiler: clang
      version: 9
    steps:
      - bash: make generate_linux build_linux
        displayName: Build
      - bash: make test_linux
        displayName: Test
  - job: osx_gcc_9
    displayName: OSX - GCC 9
    pool:
      vmImage: macOS-13
    variables:
      compiler: gcc
      version: 9
    steps:
      - bash: bash ci_scripts/travis_ci_install_osx.sh
        displayName: Install
      - bash: make generate_osx build_osx
        displayName: Build
      - bash: make test_osx
        displayName: Test
  - job: osx_gcc_12
    displayName: OSX - GCC 12
    pool:
      vmImage: macOS-13
    variables:
      compiler: gcc
      version: 12
    steps:
      - bash: bash ci_scripts/travis_ci_install_osx.sh
        displayName: Install
      - bash: make generate_osx build_osx
        displayName: Build
      - bash: make test_osx
        displayName: Test
  - job: osx_clang_12
    displayName: OSX - Clang 12
    pool:
      vmImage: macOS-13
    variables:
      compiler: clang
      version: 12
    steps:
      - bash: bash ci_scripts/travis_ci_install_osx.sh
        displayName: Install
      - bash: make generate_osx build_osx
        displayName: Build
      - bash: make test_osx
        displayName: Test
  - job: osx_clang_16
    displayName: OSX - Clang 16
    pool:
      vmImage: macOS-13
    variables:
      compiler: clang
      version: 16
    steps:
      - bash: bash ci_scripts/travis_ci_install_osx.sh
        displayName: Install
      - bash: make generate_osx build_osx
        displayName: Build
      - bash: make test_osx
        displayName: Test
  - job: windows_vs_2019
    displayName: Windows - Visual Studio 2019
    pool:
      vmImage: windows-2019
    variables:
      cmake.gen.name: Visual Studio 16 2019
      cmake.arch.arg: -A x64
    steps:
      - powershell: make generate_windows build_windows
        displayName: Build
      - powershell: make test_windows
        displayName: Test
  - job: windows_vs_2022
    displayName: Windows - Visual Studio 2022
    pool:
      vmImage: windows-2022
    variables:
      cmake.gen.name: Visual Studio 17 2022
      cmake.arch.arg: -A x64
    steps:
      - powershell: make generate_windows build_windows
        displayName: Build
      - powershell: make test_windows
        displayName: Test
  - job: lint
    displayName: Clang-Tidy Linting
    pool:
      vmImage: ubuntu-22.04
    steps:
      - bash: make lint
  - job: format
    displayName: Clang-Format
    pool:
      vmImage: ubuntu-22.04
    steps:
      - bash: make format_check
